[loader:image/svg+xml]
Exec=/usr/libexec/glycin-loaders/2+/glycin-svg
ExposeBaseDir=true
Fontconfig=true

[loader:image/svg+xml-compressed]
Exec=/usr/libexec/glycin-loaders/2+/glycin-svg
ExposeBaseDir=true
Fontconfig=true
